create table uri(
UID	INT PRIMARY KEY,
ADDRESS	VARCHAR(255),
SCODE	VARCHAR(50),
NAME	VARCHAR(255),
CONTENTTYPE	VARCHAR(100),
RETURNTYPE	VARCHAR(50),
CONTENT_TYPE	VARCHAR(255),
RETURN_TYPE	VARCHAR(255),
MESSAGE	Text
)